spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: MY-CLIENT-ID
            client-secret: MY-SECRET-KEY
            scope:
              - openid
              - profile
              - email
